USE QLDT1;
GO

--Q27--
SELECT COUNT(*) SLGV, SUM(LUONG) AS [TONG LUONG]
FROM GIAOVIEN;

--Q28--
SELECT BM.TENBM, COUNT(*) SLGV, AVG(LUONG) LUONGTB
FROM GIAOVIEN GV, BOMON BM
WHERE GV.MABM=BM.MABM
GROUP BY BM.MABM,BM.TENBM;

--Q29--
SELECT TENCD, COUNT(*) SLDT
FROM DETAI DT, CHUDE CD
WHERE DT.MACD=CD.MACD
GROUP BY CD.MACD,CD.TENCD;

--Q30--
SELECT GV.HOTEN, COUNT(DISTINCT MADT) SLDT
FROM THAMGIADT TG, GIAOVIEN GV
WHERE TG.MAGV=GV.MAGV
GROUP BY GV.MAGV,GV.HOTEN;

--Q31--
SELECT GV.HOTEN, COUNT(*) AS DTCN
FROM DETAI DT, GIAOVIEN GV
WHERE DT.GVCNDT=GV.MAGV
GROUP BY GV.MAGV,GV.HOTEN;

--Q32--
SELECT GV.HOTEN, COUNT(NT.MAGV) SLNT
FROM GIAOVIEN GV , NGUOITHAN NT
WHERE GV.MAGV=NT.MAGV
GROUP BY GV.MAGV,GV.HOTEN;

--Q33--
SELECT GV.HOTEN, COUNT(DISTINCT MADT) SLDT
FROM THAMGIADT DT, GIAOVIEN GV
WHERE DT.MAGV=GV.MAGV
GROUP BY GV.MAGV,GV.HOTEN
HAVING COUNT(DISTINCT MADT)>=3;

--Q34--
SELECT COUNT(DISTINCT GV.MAGV) SLGV
FROM THAMGIADT TG, GIAOVIEN GV, DETAI DT
WHERE TG.MAGV=GV.MAGV AND TG.MADT=DT.MADT AND DT.TENDT=N'Ứng dụng hóa học xanh';
