USE QLDT1;

--Q35--
SELECT DISTINCT GV.LUONG AS LUONGCAONHAT
FROM GIAOVIEN GV
WHERE LUONG>= ALL (SELECT LUONG
FROM GIAOVIEN);

--Q36--
SELECT HOTEN, LUONG
FROM GIAOVIEN
WHERE LUONG>=ALL(SELECT LUONG
FROM GIAOVIEN);

--Q37--
SELECT LUONG AS LUONGCAONHAT
FROM GIAOVIEN
WHERE GIAOVIEN.MABM='HTTT' AND LUONG>=ALL(SELECT LUONG
    FROM GIAOVIEN
    WHERE GIAOVIEN.MABM='HTTT');

--Q38--
SELECT HOTEN
FROM GIAOVIEN GV, (SELECT *
    FROM BOMON
    WHERE BOMON.TENBM=N'Hệ thống thông tin') BM
WHERE BM.MABM=GV.MABM AND YEAR(GV.NGSINH)<=ALL(SELECT YEAR(NGSINH)
    FROM GIAOVIEN
    WHERE GIAOVIEN.MABM=BM.MABM)


--Q39--
SELECT HOTEN
FROM (SELECT MABM
    FROM KHOA K, BOMON BM
    WHERE K.TENKHOA=N'Công nghệ thông tin'AND BM.MAKHOA=K.MAKHOA) BMCNTT, GIAOVIEN GV
WHERE BMCNTT.MABM=GV.MABM AND YEAR(GV.NGSINH)>= ALL (SELECT YEAR(GIAOVIEN.NGSINH)
    FROM GIAOVIEN
    WHERE GIAOVIEN.MABM=BMCNTT.MABM)

--Q40--
SELECT HOTEN, TENKHOA
FROM GIAOVIEN GV, KHOA K, BOMON BM
WHERE GV.MABM=BM.MABM AND K.MAKHOA=BM.MAKHOA AND GV.LUONG>=ALL(SELECT LUONG
    FROM GIAOVIEN);

--Q41--
SELECT GV.MABM, HOTEN
FROM GIAOVIEN GV
WHERE GV.LUONG>=ALL(SELECT LUONG
FROM GIAOVIEN
WHERE GV.MABM=GIAOVIEN.MABM)

--Q42--
SELECT TENDT
FROM DETAI DT, (SELECT MAGV
    FROM GIAOVIEN
    WHERE HOTEN=N'Nguyễn Hoài An') GV
WHERE TENDT<>ALL (SELECT DISTINCT TENDT
FROM THAMGIADT, DETAI
WHERE GV.MAGV=THAMGIADT.MAGV AND DETAI.MADT=THAMGIADT.MADT)

--Q43--
SELECT TENDT, GV.HOTEN AS GVQLDT
FROM DETAI DT, GIAOVIEN GV, (SELECT MAGV
    FROM GIAOVIEN
    WHERE HOTEN=N'Nguyễn Hoài An') GVA
WHERE GV.MAGV=DT.GVCNDT AND TENDT<>ALL (SELECT DISTINCT TENDT
    FROM THAMGIADT, DETAI
    WHERE GVA.MAGV=THAMGIADT.MAGV AND DETAI.MADT=THAMGIADT.MADT)

--Q44--
SELECT HOTEN
FROM (SELECT MAGV, HOTEN
    FROM GIAOVIEN, KHOA, BOMON
    WHERE GIAOVIEN.MABM=BOMON.MABM AND BOMON.MAKHOA=KHOA.MAKHOA AND KHOA.TENKHOA=N'Công nghệ thông tin') GVCNTT
WHERE NOT EXISTS(SELECT MAGV, HOTEN
FROM THAMGIADT TG
WHERE TG.MAGV=GVCNTT.MAGV)

--Q45--
SELECT GIAOVIEN.HOTEN
FROM GIAOVIEN
WHERE NOT EXISTS(SELECT HOTEN
FROM THAMGIADT TG
WHERE TG.MAGV=GIAOVIEN.MAGV)

--Q46--
SELECT GV.HOTEN
FROM GIAOVIEN GV, (SELECT *
    FROM GIAOVIEN
    WHERE GIAOVIEN.HOTEN=N'Nguyễn Hoài An') GVA
WHERE GV.LUONG>GVA.LUONG;

--Q47--
SELECT TBM.HOTEN
FROM (SELECT MAGV, HOTEN
    FROM BOMON, GIAOVIEN
    WHERE BOMON.TRUONGBM=GIAOVIEN.MAGV) TBM
WHERE EXISTS (SELECT MAGV, HOTEN
FROM THAMGIADT TG
WHERE TBM.MAGV=TG.MAGV)

--Q48--
SELECT MAGV, HOTEN
FROM GIAOVIEN GV1
WHERE EXISTS(SELECT MAGV
FROM GIAOVIEN GV2
WHERE GV1.HOTEN=GV2.HOTEN AND GV1.MABM=GV2.MABM AND GV1.MAGV<>GV2.MAGV AND GV1.PHAI=GV2.PHAI);

--Q49--*
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV
WHERE GV.LUONG>ANY(SELECT LUONG
FROM GIAOVIEN, BOMON
WHERE GIAOVIEN.MABM=BOMON.MABM AND BOMON.TENBM=N'Công nghệ phần mềm')

--Q50--
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV
WHERE GV.LUONG>ALL(SELECT LUONG
FROM GIAOVIEN, BOMON
WHERE GIAOVIEN.MABM=BOMON.MABM AND BOMON.TENBM=N'Hệ thống thông tin')

--Q51--
SELECT K.MAKHOA, TENKHOA, COUNT(MAGV) SLGV
FROM GIAOVIEN GV, KHOA K, BOMON BM
WHERE GV.MABM=BM.MABM AND BM.MAKHOA=K.MAKHOA
GROUP BY K.TENKHOA,K.MAKHOA
HAVING COUNT(*) >=ALL(SELECT COUNT(*)
FROM (SELECT TENKHOA, MAGV
    FROM GIAOVIEN GV, KHOA K, BOMON BM
    WHERE GV.MABM=BM.MABM AND BM.MAKHOA=K.MAKHOA) A
GROUP BY A.TENKHOA)
--Q52--
SELECT HOTEN
FROM GIAOVIEN GV, DETAI DT
WHERE GV.MAGV=DT.GVCNDT
GROUP BY DT.GVCNDT,GV.HOTEN
HAVING COUNT(MADT)>=ALL(SELECT COUNT(MADT)
FROM DETAI
GROUP BY DETAI.GVCNDT)

--Q53--
SELECT BM.MABM
FROM BOMON BM, GIAOVIEN GV
WHERE GV.MABM=BM.MABM
GROUP BY BM.MABM
HAVING COUNT(MAGV)>=ALL(SELECT COUNT(MAGV)
FROM BOMON BM, GIAOVIEN GV
WHERE GV.MABM=BM.MABM
GROUP BY BM.MABM)


--Q54--
SELECT GV.MAGV, GV.HOTEN, BM.TENBM
FROM BOMON BM, GIAOVIEN GV, THAMGIADT TG
WHERE GV.MAGV=TG.MAGV AND GV.MABM=BM.MABM
GROUP BY GV.HOTEN,GV.MAGV,BM.TENBM
HAVING COUNT(DISTINCT MADT)>=ALL(SELECT COUNT(DISTINCT MADT)
FROM BOMON BM, GIAOVIEN GV, THAMGIADT TG
WHERE GV.MAGV=TG.MAGV AND GV.MABM=BM.MABM
GROUP BY GV.HOTEN,GV.MAGV)

--Q55--
SELECT GV.MAGV, GV.HOTEN
FROM BOMON BM, GIAOVIEN GV, THAMGIADT TG
WHERE GV.MAGV=TG.MAGV AND GV.MABM=BM.MABM AND BM.MABM='HTTT'
GROUP BY GV.HOTEN,GV.MAGV
HAVING COUNT(DISTINCT MADT)>=ALL(SELECT COUNT(DISTINCT MADT)
FROM BOMON BM, GIAOVIEN GV, THAMGIADT TG
WHERE GV.MAGV=TG.MAGV AND GV.MABM=BM.MABM AND BM.MABM='HTTT'
GROUP BY GV.HOTEN,GV.MAGV)

--Q56--
SELECT GV.HOTEN, BM.TENBM
FROM GIAOVIEN GV, BOMON BM, NGUOITHAN NT
WHERE GV.MAGV=NT.MAGV AND GV.MABM=BM.MABM
GROUP BY GV.HOTEN,BM.TENBM
HAVING COUNT(*) >=ALL(SELECT COUNT(*)
FROM GIAOVIEN GV, BOMON BM, NGUOITHAN NT
WHERE GV.MAGV=NT.MAGV AND GV.MABM=BM.MABM
GROUP BY GV.MAGV)

--Q57--
SELECT TBM.HOTEN
FROM (SELECT MAGV, HOTEN
    FROM GIAOVIEN, BOMON
    WHERE BOMON.TRUONGBM=GIAOVIEN.MAGV) TBM, DETAI DT
WHERE DT.GVCNDT=TBM.MAGV
GROUP BY TBM.HOTEN
HAVING COUNT(MADT)>=ALL(SELECT COUNT(MADT)
FROM (SELECT MAGV, HOTEN
    FROM GIAOVIEN, BOMON
    WHERE BOMON.TRUONGBM=GIAOVIEN.MAGV) TBM, DETAI DT
WHERE DT.GVCNDT=TBM.MAGV
GROUP BY TBM.HOTEN)


