CREATE DATABASE QLGV;
GO
USE QLGV;



CREATE TABLE GIAOVIEN
(
	MAGV CHAR(5) NOT NULL,
	HOTEN NVARCHAR(20) NOT NULL,
	LUONG FLOAT NOT NULL,
	PHAI NCHAR(3) NOT NULL,
	NGSINH DATE NOT NULL,
	DIACHI NVARCHAR(50) NOT NULL,
	GVQLCM CHAR(5),
	MABM NCHAR(5) NOT NULL,
	PRIMARY KEY (MAGV)
);

CREATE TABLE BOMON
(
	MABM NCHAR(5) NOT NULL,
	TENBM NVARCHAR(20) NOT NULL,
	PHONG CHAR(5) NOT NULL,
	DIENTHOAI VARCHAR(15) NOT NULL,
	TRUONGBM CHAR(5),
	MAKHOA CHAR(5) NOT NULL,
	NGAYNHANCHUC DATE,
	PRIMARY KEY (MABM)
);

CREATE TABLE KHOA
(
	MAKHOA CHAR(5) NOT NULL,
	TENKHOA NVARCHAR(20) NOT NULL,
	NAMTL INT NOT NULL,
	PHONG CHAR(5) NOT NULL,
	DIENTHOAI VARCHAR(15) NOT NULL,
	TRUONGKHOA CHAR(5),
	NGAYNHANCHUC DATE NOT NULL,
	PRIMARY KEY(MAKHOA)
);

CREATE TABLE GV_DT
(
	MAGV CHAR(5) NOT NULL,
	DIENTHOAI VARCHAR(15) NOT NULL,
	PRIMARY KEY (MAGV,DIENTHOAI)
);

CREATE TABLE DETAI
(
	MADT CHAR(5)NOT NULL,
	TENDT NVARCHAR(50) NOT NULL,
	KINHPHI FLOAT NOT NULL,
	CAPQL NVARCHAR(10) NOT NULL,
	NGAYBD DATE NOT NULL,
	NGAYKT DATE NOT NULL,
	MACD NCHAR(5) NOT NULL,
	GVCNDT CHAR(5) NOT NULL,
	PRIMARY KEY (MADT)
);

CREATE TABLE CHUDE
(
	MACD NCHAR(5) NOT NULL,
	TENCD NVARCHAR(30) NOT NULL,
	PRIMARY KEY (MACD)
);

CREATE TABLE CONGVIEC
(
	MADT CHAR(5) NOT NULL,
	STT INT NOT NULL,
	TENCV NVARCHAR(30) NOT NULL,
	NGAYBD DATE NOT NULL,
	NGAYKT DATE NOT NULL,
	PRIMARY KEY (MADT,STT)
);

CREATE TABLE THAMGIADT
(
	MAGV CHAR(5) NOT NULL,
	MADT CHAR(5) NOT NULL,
	STT INT NOT NULL,
	PHUCAP FLOAT NOT NULL,
	KETQUA NVARCHAR(10),
	PRIMARY KEY (MAGV,MADT,STT)
);

CREATE TABLE NGUOITHAN
(
	MAGV CHAR(5) NOT NULL,
	TEN NVARCHAR(10) NOT NULL,
	NGSINH DATE NOT NULL,
	PHAI NVARCHAR(3) NOT NULL,
	PRIMARY KEY (MAGV,TEN)
);

ALTER TABLE GIAOVIEN ADD CONSTRAINT FK_GIAOVIEN_BOMON FOREIGN KEY (MABM) REFERENCES BOMON(MABM);
ALTER TABLE GIAOVIEN ADD CONSTRAINT FK_GIAOVIEN_GIAOVIEN FOREIGN KEY (GVQLCM) REFERENCES GIAOVIEN(MAGV);
ALTER TABLE GV_DT ADD CONSTRAINT FK_GV_DT_GIAOVIEN FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV);
ALTER TABLE NGUOITHAN ADD CONSTRAINT FK_NGUOITHAN_GIAOVIEN FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV);
ALTER TABLE KHOA ADD CONSTRAINT FK_KHOA_GIAOVIEN FOREIGN KEY (TRUONGKHOA) REFERENCES GIAOVIEN(MAGV);
ALTER TABLE BOMON ADD CONSTRAINT FK_BOMON_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA);
ALTER TABLE BOMON ADD CONSTRAINT FK_BOMON_GIAOVIEN FOREIGN KEY (TRUONGBM) REFERENCES GIAOVIEN(MAGV);
ALTER TABLE THAMGIADT ADD CONSTRAINT FK_THAMGIADT_GIAOVIEN FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV);
ALTER TABLE THAMGIADT ADD CONSTRAINT FK_THAMGIADT_CONGVIEC FOREIGN KEY (MADT,STT) REFERENCES CONGVIEC(MADT,STT);
ALTER TABLE CONGVIEC ADD CONSTRAINT FK_CONGVIEC_DETAI FOREIGN KEY(MADT) REFERENCES DETAI(MADT);
ALTER TABLE DETAI ADD CONSTRAINT FK_DETAI_GIAOVIEN FOREIGN KEY (GVCNDT) REFERENCES GIAOVIEN(MAGV);
ALTER TABLE DETAI ADD CONSTRAINT FK_DETAI_CHUDE FOREIGN KEY (MACD) REFERENCES CHUDE(MACD);
