USE QLDT1;


--Q1--
SELECT HOTEN, LUONG
FROM GIAOVIEN
WHERE PHAI=N'Nữ';
--Q2--
SELECT HOTEN, LUONG, LUONG*1.1 AS LUONGSAU
FROM GIAOVIEN;
--Q3--
    SELECT MAGV
    FROM GIAOVIEN
    WHERE (HOTEN LIKE N'Nguyễn%' AND LUONG>2000)

UNION
    SELECT TRUONGBM
    FROM BOMON
    WHERE ( BOMON.TRUONGBM IS NOT NULL AND YEAR(NGAYNHANCHUC)>1995);
--Q4--
SELECT HOTEN
FROM GIAOVIEN GV, BOMON BM, KHOA K
WHERE GV.MABM = BM.MABM AND BM.MAKHOA = K.MAKHOA AND K.TENKHOA = N'Công nghệ thông tin';
--Q5--
SELECT *, *
FROM BOMON, GIAOVIEN
WHERE BOMON.TRUONGBM=GIAOVIEN.MAGV;
--Q6--
SELECT GIAOVIEN.*, BOMON.*
FROM GIAOVIEN, BOMON
WHERE GIAOVIEN.MABM=BOMON.MABM;
--Q7--
SELECT TENDT, HOTEN
FROM DETAI, GIAOVIEN
WHERE DETAI.GVCNDT=GIAOVIEN.MAGV;
--Q8--
SELECT KHOA.TENKHOA, KHOA.MAKHOA, GIAOVIEN.*
FROM KHOA, GIAOVIEN
WHERE KHOA.TRUONGKHOA=GIAOVIEN.MAGV;
--Q9--
SELECT DISTINCT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV, THAMGIADT TG, BOMON BM
WHERE GV.MABM=BM.MABM AND BM.TENBM='VI SINH' AND TG.MADT='006'AND TG.MAGV=GV.MAGV;
--Q10--
SELECT DETAI.MADT, CHUDE.TENCD, GV.HOTEN, GV.NGSINH, GV.DIACHI
FROM DETAI, CHUDE, GIAOVIEN GV
WHERE DETAI.MACD=CHUDE.MACD AND GV.MAGV=DETAI.GVCNDT AND DETAI.CAPQL=N'Thành phố';
--Q11--
SELECT GIAOVIEN.HOTEN, GVCM.HOTEN AS [HO TEN GV PHU TRACH CHUYEN MON]
FROM GIAOVIEN, GIAOVIEN AS GVCM
WHERE  GIAOVIEN.GVQLCM=GVCM.MAGV;
--Q12--
SELECT GV1.HOTEN
FROM GIAOVIEN GV1, GIAOVIEN GV2
WHERE GV1.GVQLCM=GV2.MAGV AND GV2.HOTEN=N'Nguyễn Thanh Tùng';
--Q13--
SELECT HOTEN
FROM GIAOVIEN, BOMON
WHERE GIAOVIEN.MAGV=BOMON.TRUONGBM AND BOMON.TENBM=N'Hệ thống thông tin';
--Q14--
SELECT HOTEN
FROM GIAOVIEN AS GV, DETAI AS DT, CHUDE AS CD
WHERE GV.MAGV=DT.GVCNDT AND DT.MACD=CD.MACD AND CD.TENCD=N'Quản lý giáo dục';
--Q15--
SELECT CV.TENCV
FROM CONGVIEC AS CV, DETAI AS DT
WHERE DT.TENDT=N'HTTT quản lý các trường ĐH' AND (CV.NGAYBD>='2008-3-1'AND CV.NGAYBD <='2008-3-31') AND CV.MADT=DT.MADT;
--Q16--
SELECT GIAOVIEN.HOTEN, GVCM.HOTEN AS [HO TEN GV PHU TRACH CHUYEN MON]
FROM GIAOVIEN, GIAOVIEN AS GVCM
WHERE GIAOVIEN.GVQLCM IS NOT NULL AND GIAOVIEN.GVQLCM=GVCM.MAGV;
--Q17--
SELECT *
FROM CONGVIEC
WHERE CONGVIEC.NGAYBD>='2007-1-1' AND CONGVIEC.NGAYBD<='2007-8-1';
--Q18--
SELECT GV1.HOTEN
FROM GIAOVIEN GV1, GIAOVIEN GV2
WHERE GV1.MABM=GV2.MABM AND GV2.HOTEN=N'Trần Trà Hương' AND GV1.MAGV!=GV2.MAGV;
--Q19--
SELECT DISTINCT GV.HOTEN, GV.MAGV
FROM DETAI DT, BOMON BM, GIAOVIEN GV
WHERE GV.MAGV=DT.GVCNDT AND GV.MAGV=BM.TRUONGBM;
--Q20--
SELECT GV.HOTEN
FROM GIAOVIEN GV, KHOA K, BOMON BM
WHERE GV.MAGV=K.TRUONGKHOA AND GV.MAGV=BM.TRUONGBM;
--Q21--
SELECT DISTINCT GV.HOTEN, GV.MAGV
FROM DETAI DT, BOMON BM, GIAOVIEN GV
WHERE GV.MAGV=DT.GVCNDT AND GV.MAGV=BM.TRUONGBM;
--Q22--
SELECT DISTINCT K.TRUONGKHOA
FROM KHOA K, DETAI DT
WHERE K.TRUONGKHOA = DT.GVCNDT
--Q23--
SELECT DISTINCT GV.MAGV
FROM GIAOVIEN GV, BOMON BM, THAMGIADT TG
WHERE (GV.MABM='HTTT') OR (TG.MADT='001' AND TG.MAGV=GV.MAGV);
--Q24--
SELECT GV1.*
FROM GIAOVIEN GV1, GIAOVIEN GV2
WHERE GV1.MABM=GV2.MABM AND GV2.MAGV='002'AND GV1.MAGV!=GV2.MAGV;
--Q25--
SELECT GV.*
FROM GIAOVIEN GV, BOMON BM
WHERE BM.TRUONGBM=GV.MAGV;
--Q26--
SELECT HOTEN, LUONG
FROM GIAOVIEN;
