USE QLDT1
GO
DROP PROCEDURE SP_XUATDSGV
CREATE PROCEDURE SP_XUATDSGV
AS
	SELECT * FROM GIAOVIEN
SP_XUATDSGV

-------
CREATE PROCEDURE SP_SLDTCUAGV @MAGV CHAR(5)
AS
	SELECT COUNT(DISTINCT MADT) AS SLDT
	FROM THAMGIADT TG
	WHERE TG.MAGV=@MAGV
	
DROP PROCEDURE SP_SLDTCUAGV
SP_SLDTCUAGV '003'

--------------
CREATE PROCEDURE SP_INTHONGTIN @MAGV CHAR(5)
AS
BEGIN
	DECLARE @HOTEN NVARCHAR(30),@SLDT INT,@SLTN INT
	SELECT @HOTEN= HOTEN FROM GIAOVIEN GV WHERE GV.MAGV=@MAGV 
	PRINT N'Họ tên: '+@HOTEN +N' Mã GV: '+ @MAGV
	SELECT @SLDT = COUNT(DISTINCT MADT) FROM THAMGIADT TG WHERE TG.MAGV=@MAGV 
	PRINT N'SLDT = '+CAST(@SLDT AS CHAR(3))
	SELECT @SLTN=COUNT(*) FROM NGUOITHAN NT WHERE NT.MAGV=@MAGV 
	PRINT N'SLNT = '+CAST(@SLTN AS CHAR(3))
END
DROP PROCEDURE SP_INTHONGTIN
SP_INTHONGTIN '004'

------------
CREATE PROCEDURE SP_KIEMTRAGV @MAGV CHAR(5)
AS
	IF NOT EXISTS(SELECT * FROM GIAOVIEN WHERE GIAOVIEN.MAGV=@MAGV)
		RAISERROR(N'Mã Giáo viên không tồn tại',16,1)
	ELSE PRINT N'Mã Giáo viên hợp lệ' 
SP_KIEMTRAGV '001'
------------------


CREATE PROCEDURE SP_KIEMTRAQUYDINH @MAGV CHAR(5)
AS
	IF EXISTS(
	SELECT *
	FROM THAMGIADT TG,DETAI DT,BOMON BM,GIAOVIEN GVCN,GIAOVIEN GV1
	WHERE @MAGV=TG.MAGV AND DT.MADT=TG.MADT AND GVCN.MAGV=DT.GVCNDT AND GV1.MAGV=@MAGV AND GV1.MABM<>GVCN.MABM
	)
		RAISERROR(N'Vi phạm qui định',16,1)
	ELSE PRINT N'Không vi phạm qui định'
SP_KIEMTRAQUYDINH '009'

---------------
CREATE PROCEDURE SP_PHANCONG @MAGV CHAR(5),@SOTT CHAR(5),@MADT CHAR(5)
AS
BEGIN
	IF NOT EXISTS(SELECT * FROM GIAOVIEN GV WHERE GV.MAGV=@MAGV)
	BEGIN
		RAISERROR(N'MA GV KHONG TON TAI',16,1)
		RETURN
	END
	ELSE PRINT N'MA GV HOP LE'
	IF NOT EXISTS(SELECT * FROM CONGVIEC CV WHERE CV.SOTT=@SOTT AND @MADT=CV.MADT)
	BEGIN
		RAISERROR(N'CONG VIEC KHONG TON TAI',16,1)
		RETURN
	END
	ELSE PRINT N'CONG VIEC HOP LE'

	IF EXISTS(
	SELECT *
	FROM THAMGIADT TG,DETAI DT,BOMON BM,GIAOVIEN GVCN,GIAOVIEN GV1
	WHERE @MAGV=TG.MAGV AND DT.MADT=TG.MADT AND GVCN.MAGV=DT.GVCNDT AND GV1.MAGV=@MAGV AND GV1.MABM<>GVCN.MABM
	)
	BEGIN
		RAISERROR(N'Vi phạm qui định',16,1)
		RETURN
	END
	ELSE PRINT N'Không vi phạm qui định'
	INSERT INTO THAMGIADT(MAGV,MADT,STT)
	VALUES(@MAGV,@MADT,@SOTT)

END
DROP PROCEDURE SP_PHANCONG
SP_PHANCONG '002' 

---------------------
CREATE PROCEDURE SP_XOAGV @MAGV CHAR(5)
AS
BEGIN
	IF EXISTS(SELECT * FROM BOMON WHERE BOMON.TRUONGBM=@MAGV)
		RAISERROR(N'GV LAM TRUONG BO MON',16,1)
	ELSE IF EXISTS(SELECT * FROM KHOA WHERE KHOA.TRUONGKHOA=@MAGV)
		RAISERROR(N'GV LAM TRUONG KHOA',16,1)
	ELSE IF EXISTS(SELECT * FROM DETAI DT WHERE DT.GVCNDT=@MAGV)
		RAISERROR(N'GV LAM CHU NHIEM DE TAI',16,1)
	ELSE IF EXISTS(SELECT * FROM THAMGIADT TG WHERE @MAGV=TG.MAGV)
		RAISERROR(N'GV THAM GIA DE TAI',16,1)
	ELSE IF EXISTS(SELECT * FROM NGUOITHAN NT WHERE NT.MAGV=@MAGV)
		RAISERROR(N'GV CO THAN NHAN',16,1)
	ELSE IF EXISTS(SELECT * FROM GV_DT DT WHERE DT.MAGV=@MAGV)
		RAISERROR(N'GV CO SO DIEN THOAT',16,1)
	ELSE DELETE GIAOVIEN WHERE MAGV=@MAGV
END
DROP PROCEDURE SP_XOAGV
-----------------
CREATE PROCEDURE SP_QUIDINHLUONG @MAGVA CHAR(5),@MAGVB CHAR(5)
AS
BEGIN
	IF EXISTS(
	SELECT * 
	FROM BOMON BM,GIAOVIEN GV 
	WHERE BM.TRUONGBM=@MAGVA AND BM.MABM=GV.MABM AND GV.MAGV=@MAGVB)
	BEGIN
		DECLARE @LUONGA INT,@LUONGB INT
		SELECT @LUONGA = LUONG FROM GIAOVIEN WHERE MAGV=@MAGVA
		SELECT @LUONGB = LUONG FROM GIAOVIEN WHERE MAGV=@MAGVB
		IF @LUONGA<@LUONGB 
			RAISERROR(N'VI PHAM QUI DINH',16,1)
		ELSE PRINT N'KHONG VI PHAM QUI DINH'
	END
END

-----------------
CREATE PROCEDURE SP_ADDGV @MAGV CHAR(5),@HOTEN NVARCHAR(40),@NGAYSINH DATE,@LUONG INT
AS
BEGIN
	IF EXISTS(SELECT * FROM GIAOVIEN GV WHERE GV.HOTEN=@HOTEN)
		RAISERROR(N'GV BI TRUNG TEN',16,1)
	ELSE IF YEAR(GETDATE())-YEAR(@NGAYSINH)<=18
		RAISERROR(N'GV PHAI LON HON 18 TUOI',16,1)
	ELSE IF @LUONG<=0
		RAISERROR(N'LUONG PHAI LON HON 0',16,1)
	ELSE
	BEGIN
		INSERT INTO GIAOVIEN(MAGV,HOTEN,NGSINH,LUONG)
		VALUES(@MAGV,@HOTEN,@NGAYSINH,@LUONG)
	END
END

------------------------------
CREATE PROCEDURE P8 @MAKHOA CHAR(5)
AS
BEGIN
	DECLARE @VTABLE TABLE (MAGV CHAR(5))
	DECLARE @FINAL TABLE (MAGV CHAR(5),SLDT INT,SLNT INT,SLGVQL INT)

	INSERT INTO @VTABLE
	SELECT MAGV 
	FROM GIAOVIEN GV,BOMON BM
	WHERE BM.MAKHOA=@MAKHOA AND GV.MABM= BM.MABM

	DECLARE @SLGV INT
	SELECT @SLGV =COUNT(MAGV) FROM @VTABLE

	DECLARE @I INT,@MAGV CHAR(5)
	SET @I=1
	WHILE @I<=@SLGV
	BEGIN
		SELECT TOP 1 @MAGV=MAGV
		FROM @VTABLE

		DECLARE @SLDT INT,@SLNT INT,@SLGVQL INT

		SELECT @SLDT=COUNT(DISTINCT MADT)
		FROM THAMGIADT TG
		WHERE TG.MAGV=@MAGV

		SELECT @SLNT=COUNT(*)
		FROM NGUOITHAN NT
		WHERE MAGV=@MAGV

		SELECT @SLGVQL=COUNT(*)
		FROM GIAOVIEN
		WHERE GVQLCM=@MAGV

		INSERT INTO @FINAL(MAGV,SLDT,SLNT,SLGVQL)
		VALUES(@MAGV,@SLDT,@SLNT,@SLGVQL)

		DELETE @VTABLE WHERE MAGV=@MAGV
		SET @I=@I+1
	END
	SELECT * FROM @FINAL
END
DROP PROCEDURE P8
P8 'CNTT'


