USE QLDT1;
--Q75--
SELECT HOTEN, TENBM
FROM GIAOVIEN GV LEFT JOIN BOMON BM ON BM.TRUONGBM=GV.MAGV

--Q76--
SELECT TENBM, HOTEN
FROM BOMON BM LEFT JOIN GIAOVIEN GV ON GV.MAGV = BM.TRUONGBM

--Q77--
SELECT HOTEN, TENDT
FROM GIAOVIEN GV LEFT JOIN DETAI DT ON DT.GVCNDT=GV.MAGV

--Q78--
SELECT MAGV, HOTEN , CASE 
WHEN LUONG>2200 THEN N'CAO'
WHEN LUONG<=2200 AND LUONG>=1800 THEN N'TRUNG BÌNH'
WHEN LUONG<1800 THEN N'THẤP'
END MUCLUONG
FROM GIAOVIEN GV

--Q79--
SELECT MAGV, HOTEN, (SELECT COUNT(*)+1
    FROM GIAOVIEN A
    WHERE A.LUONG>GV.LUONG) HẠNG
FROM GIAOVIEN GV

--Q80--
SELECT MAGV, HOTEN,
    CASE 
    WHEN BM.MABM <> NULL THEN 300 + LUONG
    WHEN K.MAKHOA <> NULL THEN 600 + LUONG
    ELSE LUONG
    END THUNHAP
FROM GIAOVIEN GV LEFT JOIN BOMON BM ON BM.TRUONGBM=GV.MAGV LEFT JOIN KHOA K ON GV.MAGV=K.TRUONGKHOA

SELECT MAGV, HOTEN,
    (CASE PHAI 
WHEN N'Nữ' THEN YEAR(NGSINH)+55
WHEN N'Nam' THEN YEAR(NGSINH)+55
END) NAMNGHIHUU
FROM GIAOVIEN

